spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/assessment-one
spring.datasource.username=postgres
spring.datasource.password=171864
spring.jpa.hibernate.ddl-auto=update